version: "3.8"
services:
# nginx
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
# api gateway
  # immigration:
  #   image: "0816jinjin/immigration"
# endpoint service
  jeju:
    image: "smj0385/jeju"
    ports:
      - "8080:8080"
    environment:
      DB_NAME: "dis"
      DB_USER: "dis"
      DB_PASSWORD: 
      DB_HOST: 
  # gangwon:
  #   image: "toinin4795/gangwon"
  hamgyeong:
    image: "yeoul/hamgyeong"
    environment:
      SERVER_PORT: 8080
  # hwanghae:
  #   image: "toinin4795/hwanghae"
  # pyeongan:
  #   image: "0816jinjin/pyeongan"
# Repo
  dokdo:
    image: "smj0385/dokdo"
    environment:
      DB_NAME: "dis"
      DB_USER: "dis"
      DB_PASSWORD: 
      DB_HOST: 
  jeonju:
    image: "yeoul/jeonju"
    ports: 8081:8080
    environment:
      SERVER_PORT: 8080
      DB_PASSWORD: 
      DB_DATABASE: dis
      DB_USERNAME: dis
      DB_HOST: 

    
  # gyeongsang:
  #   image: "0816jinjin/gyeongsang"